<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.10.16 on linux)" generated="20241209 11:50:39.607" rpa="true" schemaversion="4">
<suite id="s1" name="Consumer" source="/app/consumer.robot">
<test id="s1-t1" name="#1   Obter Registros pendentes" line="16">
<kw name="utils.recover_pending">
<var>${status}</var>
<msg timestamp="20241209 11:50:41.088" level="FAIL">No keyword with name 'utils.recover_pending' found. Did you try using keyword '' and forgot to use enough whitespace between keyword and arguments?</msg>
<status status="FAIL" starttime="20241209 11:50:41.088" endtime="20241209 11:50:41.088"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>Status na recuperação: ${status}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" starttime="20241209 11:50:41.088" endtime="20241209 11:50:41.088"/>
</kw>
<kw name="Set Next Task" library="RPA.Tasks">
<arg>Abrir Navegador</arg>
<doc>Set the next task to be executed.
Should be a task in the same suite.</doc>
<status status="NOT RUN" starttime="20241209 11:50:41.089" endtime="20241209 11:50:41.089"/>
</kw>
<doc>Testa recuperação de registros pendentes do banco de dados</doc>
<status status="FAIL" starttime="20241209 11:50:41.081" endtime="20241209 11:50:41.089">No keyword with name 'utils.recover_pending' found. Did you try using keyword '' and forgot to use enough whitespace between keyword and arguments?</status>
</test>
<status status="FAIL" starttime="20241209 11:50:39.608" endtime="20241209 11:50:41.089"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tasks</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Consumer">Consumer</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20241209 11:50:39.608" level="ERROR">Error in file '/app/consumer.robot' on line 39: Creating keyword '' failed: User keyword name cannot be empty.</msg>
<msg timestamp="20241209 11:50:41.079" level="ERROR">Error in file '/app/consumer.robot' on line 5: Importing library '/app/utils/utils.py' failed: ModuleNotFoundError: No module named 'pymongo'
Traceback (most recent call last):
  File "/app/utils/utils.py", line 3, in &lt;module&gt;
    from pymongo import MongoClient
PYTHONPATH:
  /app/utils
  /usr/local/bin
  /usr/local/lib/python310.zip
  /usr/local/lib/python3.10
  /usr/local/lib/python3.10/lib-dynload
  /usr/local/lib/python3.10/site-packages</msg>
<msg timestamp="20241209 11:50:41.091" level="WARN">Graphviz executable not found: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH</msg>
</errors>
</robot>
